config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('accounts.urls')),
    path("", include('projetos.urls')),
    # path("projetos/", include('projetos.urls')),
    path("demanda/", include('demandas.urls')),
    path("membros/", include('membros.urls')),
    path("tarefas/", include('tarefas.urls')),
    # path('admin/', admin.site.urls),


]

demandas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('demandas_projeto/', views.demandas_projeto, name='demandas_projeto'),
    path('cadastro_novademanda/', views.cadastro_novademanda, name='cadastro_novademanda'),
    path('<int:iddemanda>', views.demanda_unico, name='demanda_unico'),
    # path('demandas/demanda/<int:iddemanda>', views.demanda_unico, name='demanda_unico'),

    path('', views.demandas, name='demandas'),
    # path('demandas/', views.demandas, name='demandas'),
    path('requisitos/<int:iddemanda>', views.requisitos, name='requisitos'),
    # path('', views.demandas, name='demandas'),
    path('alterastatus/<int:parametro>' , views.alterastatus, name='alterastatus'),

]

demandas/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User

  
class Setor(models.Model):
    setor = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.setor
    
    class Meta:
        verbose_name = 'Setor'
        verbose_name_plural = 'Setores'


class StatusBacklog(models.Model):
    status = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.status

    

class NovaDemanda(models.Model):

    nome = models.CharField(max_length=50, blank=False, null=False)
    descricao = models.TextField(max_length=255, blank=False, null=False)
    data_cadastro = models.DateTimeField(default = timezone.now)
    setor_demanda = models.ForeignKey(Setor, on_delete=models.CASCADE)
    nome_solicitante = models.CharField(max_length=255, blank=False, null=False)
    retorno_financeiro = models.DecimalField(max_digits=50, decimal_places=2, default=0, validators=[MinValueValidator(0)])
    base_calculo_retorno = models.TextField(blank=False, null=False)
    retorno_qualitativo = models.TextField( blank=False, null=False)
    link_analise = models.URLField(blank=True, null=True)
    observacao = models.TextField(blank=False, null=True)
    status_backlog = models.ForeignKey(StatusBacklog, on_delete=models.CASCADE)
    usuario_criacao = models.ForeignKey(User, on_delete=models.CASCADE) # TODO: verificar forma de buscar o usuario logado no sistema;
    

    
    def __str__(self) -> str:
        return self.nome
    
    class Meta:
        verbose_name = 'Demanda'




class Requisitos(models.Model):
    demanda = models.ForeignKey(NovaDemanda, on_delete=models.CASCADE)
    # id_demanda_requisito = models.PositiveIntegerField(default=0)
    nome = models.CharField(max_length=250, blank=False, null=False)
    descricao_requisito = models.TextField( blank=False, null=False)
    aprovacao = models.BooleanField(default=False)
    usuario_criacao = models.ForeignKey(User, on_delete=models.CASCADE) # TODO: verificar forma de buscar o usuario logado no sistema;
    # versao = models.DecimalField(max_digits=5, decimal_places=2) ### TODO: verificar se é necessario incluir

    def __str__(self) -> str:
        return self.nome
    
    class Meta:
        verbose_name = 'Requisito'

class PrioridadeUserStorie(models.Model):
    prioridade = models.CharField(max_length=50) #alta-media-baixa

    def __str__(self) -> str:
        return self.prioridade 

class UserStories(models.Model):
    requisito = models.ForeignKey(Requisitos, on_delete=models.CASCADE)
    id_storie = models.PositiveIntegerField(default=999999)
    historia = models.TextField( blank=False, null=False)    
    aceitacao = models.TextField( blank=False, null=False)
    prioridade = models.ForeignKey(PrioridadeUserStorie, on_delete=models.CASCADE)
    

    class Meta:
        verbose_name = 'UserStorie'

projetos/models.py
from django.db import models
from django.contrib.auth.models import User
from demandas.models import NovaDemanda
from django.utils import timezone


class StatusProjeto(models.Model):
    status = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.status
    
class FaseProjeto(models.Model):
    fase = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.fase
    
class PerfilUsuarios(models.Model):
    perfil = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.perfil

class NovoProjeto(models.Model):
    choices_categoria = (
        ('M', 'Melhoria'),
        ('P', 'Projeto')
    )

    nome_projeto = models.ForeignKey(NovaDemanda, null=True, on_delete=models.CASCADE)
    descricao_projeto = models.TextField(blank=False, null=False)
    status = models.ForeignKey(StatusProjeto, on_delete=models.CASCADE, null=True, blank=False)
    categoria = models.CharField(max_length=50, choices=choices_categoria, default='M')
    fase = models.ForeignKey(FaseProjeto, on_delete=models.CASCADE, null=True, blank=False)
    data_cadastro = models.DateTimeField(default = timezone.now)
    staramais = models.BooleanField(default=False)
    staralabs = models.BooleanField(default=False)
    prioridade = models.PositiveIntegerField(default=1000)
    # membros = models.ManyToManyField(User, null=True, on_delete=models.CASCADE)
    # equipe = models.ManyToManyField(User)

    def __str__ (self) -> str:
        return self.nome_projeto.nome
    
    class Meta:
        verbose_name = 'Projeto'
    
class UsuariosProjeto(models.Model):
    projeto = models.ForeignKey(NovoProjeto, null=True, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    perfil = models.ForeignKey(PerfilUsuarios, null=True, on_delete=models.CASCADE)
    recebe_email = models.BooleanField(default=False)

    class Meta:
        constraints = [
            # impede q o mesmo usuario tenha o mesmo conteudo mais que uma vez como favorito
            models.UniqueConstraint(fields=['usuario', 'projeto'], name='fav_user_content')
        ]

    

    def __int__(self) -> int:
        return self.projeto
    

class Emails(models.Model):
    projeto = models.ForeignKey(NovoProjeto, on_delete=models.DO_NOTHING)
    assunto = models.CharField(max_length=100)
    corpo = models.TextField()
    enviado = models.BooleanField()
    data_cadastro = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.assunto
    
    class Meta:
        verbose_name = 'Emails Enviado'

class Ata(models.Model):

    choices_categoria = (
        ('I', 'Informação'),
        ('P', 'Pendência'),
        ('O', 'Outros')
    )

    projeto = models.ForeignKey(NovoProjeto, on_delete=models.CASCADE)
    data_hora_reunião = models.DateTimeField(default = timezone.now)
    assunto = models.CharField(max_length=100)
    categoria = models.CharField(max_length=50, choices=choices_categoria, default='M')
    local = models.CharField(max_length=100)
    participantes = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE)
    distribuido = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE, related_name='distribuido')
    atividadeouassunto = models.TextField()
    quem = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE, related_name='quem')
    quando = models.DateField(null=True, blank=True)
    data_cadastro = models.DateTimeField(default = timezone.now)

    

tarefas/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.utils import timezone
from projetos.models import NovoProjeto, UsuariosProjeto
from datetime import timedelta

class UsuarioTarefa(models.Model):
    usuario_equipe = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE)

    def __str__ (self) -> str:
        return self.usuario_equipe


class NovaTarefa(models.Model):
    
    choices_status_tarefa = (
        ('N', 'Não Iniciado'),
        ('E', 'Em andamento'),
        ('P', 'Pendente'),
        ('C', 'Concluido')
    )

    projeto = models.ForeignKey(NovoProjeto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255, blank=False, null=False)
    descricao = models.TextField(max_length=255, blank=False, null=False)
    # membros = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE)
    status_tarefa = models.CharField(max_length=50, choices=choices_status_tarefa)
    data_criacao = models.DateTimeField(default = timezone.now)
    data_inicio_planejado = models.DateField(default = timezone.now)
    data_fim_planejado = models.DateField(default = timezone.now() + timedelta(days=10)) #add mais 10 dias caso o campo nao for preenchido;
    data_fim_realizado = models.DateTimeField(null=True, blank=True)

    def __str__ (self) -> str:
        return self.nome
    


    
    

demandas/forms.py
from django import forms
from . models import NovaDemanda

class formularioNovaDemanda(forms.ModelForm):
    class Meta:
        model = NovaDemanda
        # fields = ('nome', 
        #           'descricao',
        #           'categoria',
        #           'setor',
        #           'nome_solicitante',
        #           'retorno_financeiro',
        #           'base_calculo_retorno',
        #           'retorno_qualitativo',
        #           'link_analise',
        #           'observacao',
        #           'status',
        #           'usuario_criacao',
        #           )
        exclude = ('data_cadastro',
                   )


        # fields = '__all__'
        

demandas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
# from .forms import formularioNovaDemanda
from django.http import HttpResponse
from demandas.models import NovaDemanda, Setor, StatusBacklog, Requisitos
from projetos.models import NovoProjeto
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.messages import constants
from django.db.models import Q


@login_required(redirect_field_name='login')
def demandas_projeto(request):
    return render(request,'demandas_projeto.html')

@login_required(redirect_field_name='login')
def cadastro_novademanda(request):
    if request.method == "GET":
        # form = formularioNovaDemanda()
        status_backlog = StatusBacklog.objects.all()
        setores = Setor.objects.all()
        # user_id = request.user.id
        # # usuario_criacao = User.get_username()
        # # categoria_backlog = Categoria.objects.all()
        # print(user_id)
        
        return render(request,'cadastro_novademanda.html', {'setores': setores,
                                                            'status_backlog': status_backlog}) 
    
        
    
    elif request.method == "POST":
        nome = request.POST.get('nome')
        descricao = request.POST.get('descricao')
        # categoria  = request.POST.get('categoria')
        setor = request.POST.get('setor_demanda_id')
        nome_solicitante = request.POST.get('nome_solicitante')
        retorno_financeiro = request.POST.get('retorno_financeiro')
        base_calculo_retorno = request.POST.get('base_calculo_retorno')
        retorno_qualitativo = request.POST.get('retorno_qualitativo')
        link_analise = request.POST.get('link_analise')
        observacao = request.POST.get('observacao')
        status = request.POST.get('status')

        user_id = request.user.id
        usuario_criacao = User.objects.get(id = user_id)
        # usuario_criacao = usuario_criacao

        # print(user_id)
        # print(usuario_criacao)
        
        

        demandas = NovaDemanda(nome = nome,
                    descricao = descricao,
                    # categoria  = categoria,
                    setor_demanda_id = setor,
                    nome_solicitante = nome_solicitante,
                    retorno_financeiro = retorno_financeiro,
                    base_calculo_retorno = base_calculo_retorno,
                    retorno_qualitativo = retorno_qualitativo,
                    link_analise = link_analise,
                    observacao = observacao,
                    status = status,
                    usuario_criacao_id = user_id
                    
                    )
        
        # user_id = request.user.id
        
        # usuario_criacao = User.objects.get(id=request.id)

    
        try:
            demandas.save()
            messages.add_message(request, constants.SUCCESS, 'Demanda cadastrada com sucesso!')
            return redirect('cadastro_novademanda')
        except:
            messages.add_message(request, constants.ERROR, 'Demanda não cadastrada! Verifique os parametros digitados!' )
            return redirect('cadastro_novademanda')


        # return HttpResponse('ok')


@login_required(redirect_field_name='login')
def demandas(request):
    if request.method == "GET":
        nome_demanda_filtrar = request.GET.get('nome_demanda_filtro')
        limpar_filtros = request.GET.get('limpar_filtros')
        demandas = NovaDemanda.objects.all()
        projetos = NovoProjeto.objects.all()
        status_backlog =  StatusBacklog.objects.all()
        # print(projetos)


        demandas_sem_projeto = NovaDemanda.objects.exclude(novoprojeto__isnull=False)
        
        # print(demandas_sem_projeto)



        if limpar_filtros:
            nome_demanda_filtrar = ''


        if nome_demanda_filtrar:
            demandas = demandas.filter(nome__icontains=nome_demanda_filtrar)

        

        return render(request, 'demandas.html', {'demandas': demandas,
                                                'projetos': projetos,
                                                'demandas_sem_projeto':demandas_sem_projeto,
                                                'status_backlog': status_backlog
                                                })
    # elif request.method == "POST":
    #     status_modal = request.POST.get('status_modal')
    #     print(status_modal)

    #     demandas = NovaDemanda(status = status_modal) #TODO: verificar como salvar a alteração;
           
    #     demandas.save()
    #     return redirect('demandas')


@login_required(redirect_field_name='login')
def demanda_unico (request, iddemanda):
    demanda_unico = get_object_or_404(NovaDemanda, id=iddemanda)
    # demanda_unica = NovaDemanda.objects.get(id=)
    status_backlog = StatusBacklog.objects.all()
    # faseprojeto = FaseProjeto.objects.all()

    return render(request, 'demanda_unico.html', {'demanda': demanda_unico,
                                                 'demandas':demandas,
                                                 
                                                 })

@login_required(redirect_field_name='login')
def alterastatus(request, parametro):
    if request.method == "POST":
        status_backlog = request.POST.get('status_backlog')       
        id_demanda = get_object_or_404(NovaDemanda, id=parametro)
        id_demanda.status_backlog_id = status_backlog        
        id_demanda.save()
        return redirect('demandas')

@login_required(redirect_field_name='login')
def requisitos(request, iddemanda):
    if request.method == "GET":
        id_demanda = get_object_or_404(NovaDemanda, id=iddemanda)


        print(iddemanda)

        requisitos = Requisitos.objects.filter(demanda_id=iddemanda)

        print(requisitos)
        # content = {'demanda': id_demanda,
        #            'requisitos': requisitos}

        return render(request, 'requisitos.html', {'requisitos': requisitos,
                                                   'demanda': id_demanda} )

demandas/templates/cadastro_novademanda.html
{% extends 'base.html' %}



{% block titulo %}Cadastro Nova Demanda |{% endblock titulo %}

{% block 'head' %}
{% load static %}

<link href="{% static 'demandas/css/demanda.css' %}" rel="stylesheet">

{% endblock %}

{% block 'body' %}

    <div class="wrapper">
        <div class="box">
            <div class="header">
                <h3 class="titulo">Cadastro de Demanda</h3>
            </div>

                {% comment %} mensagem de alerta! {% endcomment %}
                {% include "parciais/_messages.html" %}
                {% comment %} mensagem de alerta! {% endcomment %}

            <div class="body-box">
                <form action="{% url 'cadastro_novademanda' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="row">
                    <div class="col-md">
                        <label>Nome:</label>
                        <input type="text" class="form-control" name="nome" placeholder="Digite o nome da demanda...">
                    </div>
                    </div>
                    <br>
                    <div class="row">
                    </div>                    
                    <div class="row">
                        <div class="col-md">
                            <label>Descrição da demanda:</label>
                            <textarea name="descricao" class="form-control" placeholder="Descreve o objetivo da demanda..."></textarea>
                        </div>
                    </div>
                    <br>   
                    <div class="row">
                        <div class="col-md">
                            <label>Status:</label>
                                <select class="form-select input-tarefa" name="setor_demanda_id">
                                    {% for status in status_backlog %}
                                        <option value={{status.id}}>{{status}}</option>
                                    {% endfor %} 
                                </select>
                        </div>
                    </div>
                    <br> 
                    <div class="row">
                        <div class="col-md">
                            <label>Setor:</label>
                                <select class="form-select input-tarefa" name="setor_demanda_id">
                                    {% for setor in setores %}
                                    
                                        <option value={{setor.id}}>{{setor}}</option>
                
                                    {% endfor %}   
                
                                </select>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                    <div class="col-md">
                        <label>Nome Solicitante:</label>
                        <input type="text" class="form-control" name="nome_solicitante" placeholder="Nome do solicitante...">
                    </div>
                    </div>
                    <br>

                    <div class="row">
                        <div class="col-md">
                            <label>Retorno Financeiro:</label>
                            <input type="number" step="0.1" name="retorno_financeiro">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Base do calculo de retorno:</label>
                            <textarea name="base_calculo_retorno " class="form-control" placeholder="Digite como foi realizado o calculo de retorno..."></textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Retorno qualitivo:</label>
                            <textarea name="retorno_qualitativo" class="form-control" placeholder="Descreva o retorno que não podera ser quantificado..."></textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Observação:</label>
                            <textarea name="observacao" class="form-control" placeholder="Caso necessario descreva alguma observação..."></textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Link Analise:</label>
                            <input type="url" name="link_analise" size="50" >
                        </div>
                    </div>
                    <br>
                    

                    
                    




                    <input type="submit" value="Novo Cadastro" class="btn btn-lg btn-orange">
                </form>
                
            </div>
        </div>
    </div>
   
{% endblock%}

demandas/templates/demanda_unico.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'demandas/css/demanda_unico.css' %}" rel="stylesheet">
{% endblock%}


{% block 'body' %}

    
    <br>
    <div class="container">
        {% include "parciais/_messages.html" %}
        
        {% comment %} <form id="projeto_select" action="{% url 'demanda_unico' demanda.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %} {% endcomment %}
            <div class="row">         
                <div class="col-md">
                    <h1 id="id_projeto" class="titulo">{{demanda.nome}}</h1>
                </div>         
            </div>
            <br>
            <div class="row">
                <div class="col-md">
                    <div >
                        <label>Descricão do projeto ou melhoria:</label>
                        <p>{{demanda.descricao}}</p>
                    </div>
                </div>
            </div>
            <hr>

            {% comment %} <button type="button" class="btn btn-secondary">Requisitos<a href="{% url 'demandas_projeto' %}"></a></button>  {% endcomment %}
            <a class="btn btn-secondary" href="{% url 'requisitos' iddemanda=demanda.id %}">Requisitos</a>
            {% comment %} #TODO: criar tela para cadastro de requisitos; {% endcomment %}
            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalata">Tests Cases</button> 
            {% comment %} #TODO: criar tela para cadastro dos testes; {% endcomment %}
            <hr>               

            {% comment %} <div class="row">
                <div class="col-md-7">
                    <label>Categoria:</label>
                    <label disabled class="form-control">{{projeto.get_categoria_display}}</label>
                </div>
            </div> {% endcomment %}
            <div class="row">
                <div class="col-md-7">
                    <label>Status:</label>
                    <label disabled class="form-control">{{demanda.status_backlog}}</label>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-7">
                    <label>Setor:</label>
                    <label disabled class="form-control">{{demanda.setor_demanda}}</label>
                </div>
            </div>

            <br> 
            <div class="row">
                <div class="col-md-7">
                    <div >
                        <label>Retorno Financeiro:</label>
                        <p>{{demanda.retorno_financeiro}}</p>
                    </div>
                </div>
            </div>

            <br> 
            <div class="row">
                <div class="col-md-7">
                    <div >
                        <label>Calculo retorno:</label>
                        <p>{{demanda.base_calculo_retorno}}</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-7">
                    <div >
                        <label>Retorno Qualitativo:</label>
                            <p>{{demanda.retorno_qualitativo}}</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md">
                    <div >
                        <label>Link Analise:</label>
                            <a href="{{demanda_unica.link_analise}}">{{demanda.link_analise}}</a>
                    </div>
                </div>
            </div>
            
            <br>
            


            <hr>
            <div class="row">
                <div class="col-md-7">
                    <label>Nome solicitante:</label>
                    <label disabled class="form-control">{{demanda.nome_solicitante}}</label>
                </div>
            </div>
            <div class="row">
                <div class="col-md-7">
                    <label>Data Cadastro:</label>
                    <label disabled class="form-control">{{demanda.data_cadastro}}</label>
                </div>
            </div>
            
            <hr>
            <br>
            

    </div>
{% endblock %}

demandas/templates/demandas_projeto.html
{% extends 'base.html' %}

{% block 'head' %}
{% load static %}

<link href="{% static 'base/css/projeto_demanda.css' %}" rel="stylesheet">

{% endblock %}

{% block titulo %}Novo Cadastro-{% endblock titulo %}

{% block 'conteudo' %}

    <body >
        <div class="pag">
            <ul class="ul1">
                <div class="li1">
                    <div class="li2">
                        <img class="img1" src="{% static 'fotos/pana.png' %}" alt="">
                        </div>
                            <button class="btn">
                                <a class = "a_link" href="{% url 'cadastro_novademanda' %}">Nova Demanda</a>                    
                            </button>                            
                        </div>
                    </div>
                </div>
            </ul>
        </div>                   
        <div class="pag">
            <ul class="ul1">
                <div class="li1">
                    <div class="li2">
                        <img class="img1" src="{% static 'fotos/rafiki.png' %}" alt="">
                        </div>
                            <button class="btn">
                                <a class = "a_link"  href="{% url 'novo_projeto' %}" >Novo Projeto</a>                  
                            </button>                            
                        </div>
                    </div>
                </div>
            </ul>
        </div>          

            
            
       
    </body>



{% endblock 'conteudo' %}

demandas/templates/modal_alterar_status.html
{% load static %}

{% comment %} thanks https://www.youtube.com/watch?v=P78-ltyeuVg {% endcomment %}

<!-- Modal = Alterar Status Demanda -->
{% for demanda in demandas %}
    <form action="{% url 'alterastatus' demanda.id %}" method='POST' enctype="multipart/form-data">{% csrf_token %}

        <div class="modal fade" id="alterarstatusdemanda-{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Alterar Status</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md">
                        <label>Status:</label>
                            <select class="form-select input-tarefa" name="status_backlog">
                                {% for status in status_backlog %}                                
                                    <option value="{{ status.id }}" {% if demanda.status_backlog_id == status.id %}selected{% endif %}>
                                        {{ status.status }}
                                    </option>  
                                {% endfor %} 

                                 
                            </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar">
                <input type="submit" value="Salvar" class="btn btn-orange">
            </div>
            </div>
        </div>
        </div>

    </form>
{% endfor %}

demandas/templates/modal_visualiza_requisito.html
{% load static %}

<!-- Modal Nova Tarefa-->
<div class="modal fade" id="ModalVisualizaRequisito" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
    <div class="modal-header">
        <h5 style="font-size: 30px" class="modal-title titulo" id="exampleModalLabel">Descrição do Requisito</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    
        <div class="modal-body">				
            <textarea class="form-control" rows="5">{{requisito.descricao_requisito}}</textarea>    
        </div>
    
        {% comment %} <div class="modal-body">				
            <label>Requisito:</label>
            <textarea name="descricao_requisito" class="form-control" placeholder="Descrever um requisito que possa ser testável..."></textarea>
            
        </div> {% endcomment %}
        
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Sair</button>
        </div>

    

</div>
</div>