config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('accounts.urls')),
    path("", include('projetos.urls')),
    # path("projetos/", include('projetos.urls')),
    path("demanda/", include('demandas.urls')),
    path("membros/", include('membros.urls')),
    path("tarefas/", include('tarefas.urls')),
    # path('admin/', admin.site.urls),


]

projetos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.projetos, name='projetos'),
    path('novo_projeto/', views.novo_projeto, name='novo_projeto'),
    path('projeto/<int:id>', views.projeto_unico, name='projeto_unico'),
    # path('editar_projeto/<int:id>/', views.editar_projeto, name='editar_projeto'),
    path('novo_projeto/add_usuarios_projeto/', views.add_usuarios_projeto, name='add_usuarios_projeto'),
    # path('<int:id>/usuarios_projeto/', views.usuarios_projeto, name='usuarios_projeto'),

    path('envia_email/<int:id_projeto>', views.envia_email, name="envia_email"),
    
    path('update/<int:id>', views.updateprojeto, name="updateprojeto")
 
    


    #VERIFICAR
    # path('cronograma/', views.cronograma, name='cronograma'),
    # path('membros/', views.membros, name='membros'),   
    # path('resultado/', views.resultado, name='resultado'),
    
]

tarefas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('novatarefa/', views.novatarefa, name='nova_tarefa'),
    # path('tarefa/<int:id>', views.tarefa, name='tarefa'),
    path('tarefas/', views.tarefas, name='tarefas'),
    path('tarefa/<int:id>', views.tarefa_unica, name='tarefa_unica'),
    path('', views.tarefas, name='tarefas'),
    path('tarefas/alteraprojeto/', views.alteraprojeto, name='alteraprojeto')
]

projetos/models.py
from django.db import models
from django.contrib.auth.models import User
from demandas.models import NovaDemanda
from django.utils import timezone


class StatusProjeto(models.Model):
    status = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.status
    
class FaseProjeto(models.Model):
    fase = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.fase
    
class PerfilUsuarios(models.Model):
    perfil = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.perfil

class NovoProjeto(models.Model):
    choices_categoria = (
        ('M', 'Melhoria'),
        ('P', 'Projeto')
    )

    nome_projeto = models.ForeignKey(NovaDemanda, null=True, on_delete=models.CASCADE)
    descricao_projeto = models.TextField(blank=False, null=False)
    status = models.ForeignKey(StatusProjeto, on_delete=models.CASCADE, null=True, blank=False)
    categoria = models.CharField(max_length=50, choices=choices_categoria, default='M')
    fase = models.ForeignKey(FaseProjeto, on_delete=models.CASCADE, null=True, blank=False)
    data_cadastro = models.DateTimeField(default = timezone.now)
    staramais = models.BooleanField(default=False)
    staralabs = models.BooleanField(default=False)
    prioridade = models.PositiveIntegerField(default=1000)
    # membros = models.ManyToManyField(User, null=True, on_delete=models.CASCADE)
    # equipe = models.ManyToManyField(User)

    def __str__ (self) -> str:
        return self.nome_projeto.nome
    
    class Meta:
        verbose_name = 'Projeto'
    
class UsuariosProjeto(models.Model):
    projeto = models.ForeignKey(NovoProjeto, null=True, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    perfil = models.ForeignKey(PerfilUsuarios, null=True, on_delete=models.CASCADE)
    recebe_email = models.BooleanField(default=False)

    class Meta:
        constraints = [
            # impede q o mesmo usuario tenha o mesmo conteudo mais que uma vez como favorito
            models.UniqueConstraint(fields=['usuario', 'projeto'], name='fav_user_content')
        ]

    

    def __int__(self) -> int:
        return self.projeto
    

class Emails(models.Model):
    projeto = models.ForeignKey(NovoProjeto, on_delete=models.DO_NOTHING)
    assunto = models.CharField(max_length=100)
    corpo = models.TextField()
    enviado = models.BooleanField()
    data_cadastro = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.assunto
    
    class Meta:
        verbose_name = 'Emails Enviado'

class Ata(models.Model):

    choices_categoria = (
        ('I', 'Informação'),
        ('P', 'Pendência'),
        ('O', 'Outros')
    )

    projeto = models.ForeignKey(NovoProjeto, on_delete=models.CASCADE)
    data_hora_reunião = models.DateTimeField(default = timezone.now)
    assunto = models.CharField(max_length=100)
    categoria = models.CharField(max_length=50, choices=choices_categoria, default='M')
    local = models.CharField(max_length=100)
    participantes = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE)
    distribuido = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE, related_name='distribuido')
    atividadeouassunto = models.TextField()
    quem = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE, related_name='quem')
    quando = models.DateField(null=True, blank=True)
    data_cadastro = models.DateTimeField(default = timezone.now)

    

tarefas/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.utils import timezone
from projetos.models import NovoProjeto, UsuariosProjeto
from datetime import timedelta

class UsuarioTarefa(models.Model):
    usuario_equipe = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE)

    def __str__ (self) -> str:
        return self.usuario_equipe


class NovaTarefa(models.Model):
    
    choices_status_tarefa = (
        ('N', 'Não Iniciado'),
        ('E', 'Em andamento'),
        ('P', 'Pendente'),
        ('C', 'Concluido')
    )

    projeto = models.ForeignKey(NovoProjeto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255, blank=False, null=False)
    descricao = models.TextField(max_length=255, blank=False, null=False)
    # membros = models.ForeignKey(UsuariosProjeto, on_delete=models.CASCADE)
    status_tarefa = models.CharField(max_length=50, choices=choices_status_tarefa)
    data_criacao = models.DateTimeField(default = timezone.now)
    data_inicio_planejado = models.DateField(default = timezone.now)
    data_fim_planejado = models.DateField(default = timezone.now() + timedelta(days=10)) #add mais 10 dias caso o campo nao for preenchido;
    data_fim_realizado = models.DateTimeField(null=True, blank=True)

    def __str__ (self) -> str:
        return self.nome
    


    
    

projetos/forms.py
# from django import forms
# from projetos.models import NovoProjeto

# class FormularioNovoProjeto(forms.ModelForm):
#     class Meta:
#         model = NovoProjeto
#         # fields = ('nome', 
#         #           'descricao',
#         #           'categoria',
#         #           'setor',
#         #           'nome_solicitante',
#         #           'retorno_financeiro',
#         #           'base_calculo_retorno',
#         #           'retorno_qualitativo',
#         #           'link_analise',
#         #           'observacao',
#         #           'status',
#         #           'usuario_criacao',
#         #           )
#         exclude = ('data_cadastro',)


#         # fields = '__all__'
        

projetos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages, auth
from django.core.validators import validate_email
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages import constants
from django.http import HttpResponse, JsonResponse
from django.core import serializers
import json
from django.urls import reverse
from django.core.mail import EmailMultiAlternatives
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.conf import settings
from demandas.models import NovaDemanda
from tarefas.models import NovaTarefa
from projetos.models import StatusProjeto, FaseProjeto, NovoProjeto, PerfilUsuarios, UsuariosProjeto, Emails


@login_required(redirect_field_name='login')
def novo_projeto(request):
    if request.method == "GET":
    # form = FormularioNovoProjeto()
        demandas = NovaDemanda.objects.all()
        statusprojeto = StatusProjeto.objects.all()
        faseprojeto = FaseProjeto.objects.all()
        usuarios = User.objects.all()
        perfis = PerfilUsuarios.objects.all()

        return render(request,'cadastro_projeto.html', {'demandas':demandas, #TODO: filtrar demanda que estão em aberto.
                                                        'statusprojeto':statusprojeto,
                                                        'faseprojeto':faseprojeto,
                                                        'usuarios':usuarios,
                                                        'perfis': perfis
                                                        })
    
    elif request.method == "POST":
        nome_projeto_id = request.POST.get('nomeprojeto')
        descricao_projeto = request.POST.get('descricao_projeto')
        status_id = request.POST.get('statusprojeto')
        fase_id = request.POST.get('faseprojeto')
        categoria  = request.POST.get('categoria')


        if request.POST.get('staramais') == None:    
            staramais = False
        else:
            staramais = True
        
        if request.POST.get('staralabs') == None:
            staralabs = False
        else:
            staralabs = True
        
        prioridade = request.POST.get('prioridade')
        user_id = request.POST.getlist('equipe')

     
        # demanda_id = request.POST.get('nomeprojeto')
        # demanda = NovaDemanda.objects.get(id=demanda_id)

        projeto = NovoProjeto(nome_projeto_id = nome_projeto_id,
                    status_id = status_id,
                    fase_id  = fase_id,
                    categoria  = categoria,
                    staramais = staramais,
                    staralabs = staralabs,
                    prioridade = prioridade,
                    descricao_projeto = descricao_projeto,
                
                    )
    

        if NovoProjeto.objects.filter(nome_projeto_id=nome_projeto_id).exists():
            messages.add_message(request, constants.ERROR, 'Projeto já cadastrado!')
            return redirect('novo_projeto')
        
        
    try:
        projeto.save()
        projeto.equipe.add(*user_id)
        projeto.save()
        messages.add_message(request, constants.ERROR, 'Projeto não cadastrado! Verifique os parametros digitados!' )
        return redirect('novo_projeto')
                        
    
    except:
        
        messages.add_message(request, constants.SUCCESS, 'Projeto cadastrado com sucesso!')
        return redirect('novo_projeto')  


@login_required(redirect_field_name='login')
def envia_email(request, id_projeto):
    if request.method == 'POST':
        projeto_unico = NovoProjeto.objects.get(id=id_projeto)
        usuarios_projeto = UsuariosProjeto.objects.filter(recebe_email=1, projeto_id=id_projeto)
        # usuarios = User.objects.filter(id=4)

        ids_usuarios_projeto = usuarios_projeto.values_list('usuario_id', flat=True)

        usuarios = User.objects.filter(id__in=ids_usuarios_projeto)



        # print(usuarios)
        #TODO: fazer validacao se o projeto selecionado possui algum usuario que recebe email;

        # for usuarioa in usuarios_projeto:
        #     print(usuarioa.usuario_id)

        email_usuarios = [usuario.email for usuario in usuarios]
        usuario = [usuario.first_name for usuario in usuarios]


        # if email_usuarios == '':
        #     messages.add_message(request, constants.ERROR, 'Projeto não possui usuarios que recebem email!')
        #     return redirect(f'/projeto/{id_projeto}')

             
        

        
        assunto = request.POST.get('assunto')
        corpo = request.POST.get('corpo')

        contexto = {'usuario': usuario, 
                    'projeto_unico': projeto_unico,
                    'corpo': corpo
                    }
        

        html_content = render_to_string('emails/report_projeto.html',
                                        contexto
                                        )
        
        text_content = strip_tags(html_content)

        email = EmailMultiAlternatives(assunto, 
                                    text_content, 
                                    settings.EMAIL_HOST_USER,
                                    email_usuarios,
                                    )
        
        email.attach_alternative(html_content, "text/html")

        email.send()



        if len(email_usuarios) == 0:
            messages.add_message(request, constants.ERROR, 'Projeto não possui usuarios que recebem email!')
            return redirect(f'/projeto/{id_projeto}') 

        elif email.send():
            mail = Emails(
                projeto=projeto_unico,
                assunto=assunto,
                corpo=corpo,
                enviado=True
            )
            mail.save()
            messages.add_message(request, constants.SUCCESS, 'Email enviado com sucesso.')
            return redirect(f'/projeto/{id_projeto}')    
                
        
        else:
            mail = Emails(
                projeto=projeto_unico,
                assunto=assunto,
                corpo=corpo,
                enviado=False
            )
            mail.save()
            messages.add_message(request, constants.ERROR, 'Erro interno do sistema!')
            return redirect(f'/projeto/{id_projeto}') 
                

@login_required(redirect_field_name='login')
def add_usuarios_projeto(request):
    if request.method == 'GET':
        usuarios = User.objects.all()
        perfil = PerfilUsuarios.objects.all()
        usuarios_json = json.loads(serializers.serialize('json', usuarios))
        perfil_json = json.loads(serializers.serialize('json', perfil))
        usuarios_json_f = [{'user': i['fields'], 'id': i['pk']} for i in usuarios_json]
        perfil_json_f = [{'perfil': i['fields'], 'id': i['pk']} for i in perfil_json]




        # for a in usuarios:
        #     print(a.id)

        # print(perfil_json)
      
        return JsonResponse({'usuarios': usuarios_json_f,
                             'perfil': perfil_json_f
                             })


#     id_projeto = request.POST.get('id_projeto')
#     projeto = NovoProjeto.objects.filter(nome_projeto_id=id_projeto)
#     usuarios = UsuariosProjeto.objects.filter(projeto=projeto[0])
#     projeto_json = json.loads(serializers.serialize('json', projeto))[0]['fields']
#     projeto_id = json.loads(serializers.serialize('json', usuarios))
#     usuarios_json = json.loads(serializers.serialize('json', usuarios))
#     usuarios_json_f = [{'fields': i['fields'], 'id': i['pk']} for i in usuarios_json]
#     lst_usuarios_json = [json.loads(serializers.serialize('json', User.objects.filter(id=usuarioss['fields']['usuario']))) for usuarioss in usuarios_json_f]
#     perfil_usuarios_json = [{'fields': i['fields'], 'perfil': i['pk']} for i in usuarios_json]
#     perfil_usuario_projeto = [json.loads(serializers.serialize('json', PerfilUsuarios.objects.filter(id=perfils['fields']['perfil']))) for perfils in perfil_usuarios_json] 
#     data = {'usuario': lst_usuarios_json, 'projetos': projeto_json, 'projeto_id': projeto_id, 'perfil':perfil_usuario_projeto}
    
    elif request.method == "POST":
    
        pass


@login_required(redirect_field_name='login')
def projetos (request):
    nome_projeto_filtrar = request.GET.get('nome_projeto_filtro')
    status_projeto_filtrar = request.GET.get('status_projeto_filtrar')
    limpar_filtros = request.GET.get('limpar_filtros')
    fase_projeto_filtrar = request.GET.get('fase_projeto_filtrar')

    projeto = NovoProjeto.objects.all()
    status_projeto = StatusProjeto.objects.all()
    fase_projeto = FaseProjeto.objects.all()

    if limpar_filtros:
        nome_projeto_filtrar = ''
        status_projeto_filtrar = ''

    if nome_projeto_filtrar:
        projeto = projeto.filter(nome_projeto__nome__icontains=nome_projeto_filtrar)
    
    if status_projeto_filtrar:
        projeto = projeto.filter(status_id=status_projeto_filtrar)

    # if status_projeto_filtrar:
    #     projeto = projeto.filter(fase_id=fase_projeto_filtrar)

    

    return render(request, 'projetos.html', {'projeto': projeto,
                                             'status_projeto': status_projeto,
                                             'fase_projeto': fase_projeto})

@login_required(redirect_field_name='login')
def projeto_unico (request, id):
    projeto_unico = get_object_or_404(NovoProjeto, id=id)
    demanda_unica = NovaDemanda.objects.get(id=projeto_unico.nome_projeto_id)
    status = StatusProjeto.objects.all()
    faseprojeto = FaseProjeto.objects.all()
    total_tarefas = NovaTarefa.objects.filter(projeto_id = id).count()
    total_tarefas_nao_concluidas = NovaTarefa.objects.filter(projeto_id = id, status_tarefa='C').count()

    if total_tarefas_nao_concluidas != 0:

projetos/templates/modal_usuarios_cadastrados.html
{% load static %}

<!-- Modal Exibe os Usarios do projeto, vai buscar atraves do %include% -->

<div class="modal fade" id="modalusuariocadastrados" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title titulo" id="myModalLabel">Usuarios Cadastrados no Projeto</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
            </div>
                <div class="modal-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Perfil</th>
                                <th>Recebe Email?</th>
                            </tr>   
                        </thead>
                        <tbody>                    
                            <td>
                                {% for usuario_projeto in usuarios_projeto %}
                                    <p>{{usuario_projeto.usuario}}</p>
                                {% endfor %}
                            </td>
                            <td>
                                {% for usuario_projeto in usuarios_projeto %}
                                    <p>{{usuario_projeto.perfil}}</p>
                                {% endfor %}
                            </td>
                            <td>
                                {% for usuario_projeto in usuarios_projeto %}
                                
                                    {% if usuario_projeto.recebe_email == 1 %}                                        
                                        <img src="{% static 'projetos/svg/ok.svg' %}" alt="">                                        
                                    {% else %}
                                        <img src="{% static 'projetos/svg/cancel.svg' %}" alt="">                                  
                                    {% endif %}
                                    <br>
                                {% endfor %}
                            </td>
                        </tbody>
                    </table>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Sair</button>
                    </div>
                </div>
        </div>
    </div>
</div>

projetos/templates/projeto_unico.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'projetos/css/projeto_unico.css' %}" rel="stylesheet">
{% endblock%}


{% block 'body' %}

   

    
    <br>
<div class="container">

    {% include "parciais/_messages.html" %}
        
        
    <form id="projeto_select" action="{% url 'projeto_unico' projeto.id %}" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">         
            <div class="col-md">
                <h1 id="id_projeto" class="titulo">{{projeto.nome_projeto}}</h1>
            </div>         
        </div>
        
        <br>
        <div class="row">
            <div class="col-md">
                <div style="max-width: 100%; word-wrap: break-word;">
                    <label>Descricão do projeto ou melhoria:</label>
                    <p >{{projeto.descricao_projeto}}</p>
                    {% comment %} #TODO: verificar para quebrar a linha; {% endcomment %}
                </div>
            </div>
        </div>
        <br>
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalusuariocadastrados">Usuarios Cadastrados</button>
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalata">Cadastro Ata</button>
        
        <hr>
        <div class="col-md-7">
                <label>Progresso Atual:</label>                        
                    <div style="width: 100%" class="progress">
                        <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: {{ percentual_projeto }}%" aria-valuenow="{{ percentual_projeto }}" aria-valuemin="0" aria-valuemax="100">{{ percentual_projeto }}%</div>
                    </div>
        </div>
        <hr>

        <div class="row">
            <div class="col-md-7">
                <label>Categoria:</label>
                <label disabled class="form-control">{{projeto.get_categoria_display}}</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <label>Status:</label>
                <label disabled class="form-control">{{projeto.status}}</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <label>Fase:</label>
                <label disabled class="form-control">{{projeto.fase}}</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <label>Setor:</label>
                <label disabled class="form-control">{{demanda_unica.setor_demanda}}</label>
            </div>
        </div>

        <br> 
        <div class="row">
            <div class="col-md-7">
                <div >
                    <label>Retorno Financeiro:</label>
                    <p>{{demanda_unica.retorno_financeiro}}</p>
                </div>
            </div>
        </div>

        <br> 
        <div class="row">
            <div class="col-md-7">
                <div >
                    <label>Calculo retorno:</label>
                    <p>{{demanda_unica.base_calculo_retorno}}</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-7">
                <div >
                    <label>Retorno Qualitativo:</label>
                        <p>{{demanda_unica.retorno_qualitativo}}</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md">
                <div >
                    <label>Link Analise:</label>
                        <a href="{{demanda_unica.link_analise}}">{{demanda_unica.link_analise}}</a>
                </div>
            </div>
        </div>
        
        <br>      


        <hr>
        <div class="row">
            <div class="col-md-7">
                <label>Nome solicitante:</label>
                <label disabled class="form-control">{{demanda_unica.nome_solicitante}}</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <label>Data Cadastro:</label>
                <label disabled class="form-control">{{demanda_unica.data_cadastro}}</label>
            </div>
        </div>
    </form>            
                 
        
        

        {% comment %} Modal dos usuarios {% endcomment %}
        {% include "modal_usuarios_cadastrados.html" %}
        {% include "modal_atas.html" %}                     
                     

      

        

      
        
    
        

    
</div>
<br>


<div class="container bg3">                
            <div class="row">
                <div class="col-md">
                    <p>Envie e-mails do Status Report por aqui.</p>
                </div>

                <div class="col-md">
                    <form action="{% url 'envia_email' projeto.id %}" method='POST'>{% csrf_token %}
                        <label>Assunto:</label>
                        <input name="assunto" type="text" class="form-control" placeholder="assunto">
                        <br>
                        <label>Informações adicionais:</label>
                        <textarea name="corpo" class="form-control"></textarea>
                        <br>
                        <input type="submit" class="btn btn-orange" value="Enviar">
                    </form>
                </div>
            </div>
        </div>


<script src="{% static 'projetos/js/projeto_unico.js' %}"></script>   
{% endblock %}

projetos/templates/projetos.html
{% extends 'base.html' %}

{% block titulo %}Inicio |{% endblock titulo %}

{% load static %}

{% load filtro %}


{% block 'head' %}
    <link href="{% static 'projetos/css/projetos.css' %}" rel="stylesheet">
{% endblock%}

{% block 'body' %}
    
        <h1>
            <p class="mb-2">Olá, {{user.first_name}} {{user.last_name }} </p>
        </h1>
            {% include 'parciais/_messages.html' %}
    <br>
    <div class="card-deck">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Projetos Concluidos</h5>
                <h1 class="card-text">2</h1>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Projetos Em Andamento</h5>
                <h1 class="card-text">10</h1>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Projetos Não Iniciado</h5>
                <h1 class="card-text">5</h1>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Backlog</h5>
                <h1 class="card-text">15</h1>
            </div>
        </div>
    </div>

    <div class="wrapper">
        <div class="box"> 
            <div class="header-box">
                {% if messages %}
                    {% for message in messages %}
                        <section class="alert {{message.tags}}">
                            {{message}}
                        </section>
                    {% endfor %}
                {% endif %}

                
                

                

                <h2 class="titulo">Gestão de Projetos</h2>
                <a href="{% url 'novo_projeto' %}" class="btn-nova-empresa">Novo projeto</a>
                
                <a href="{% url 'cadastro_novademanda' %}" class="btn-nova-empresa">Nova demanda</a>
                <br>
            </div>
            <div class="borda-box"></div>
            <div class="body-box">
            
                <form action="#" method="GET">
                    {% csrf_token %}
                <div class="row">
                    
                        <div class="col-md-5">
                            <h6>Nome projeto</h6>
                            <input type="text" placeholder="Busque pelo nome projeto..." class="form-control" name="nome_projeto_filtro">
                        </div>

                        <div class="col-md-2">
                            <h6>Status</h6>
                            <select class="form-control" name="status_projeto_filtrar" >
                                {% for status_projetos in status_projeto %}
                                    <option value="{{status_projetos.id}}">{{status_projetos}}</option>
                                {% endfor %}
                            </select>
                        </div>

                        {% comment %} <div class="col-md-2">
                            <h6>Fase</h6>
                            <select class="form-control" name="fase_projeto_filtrar">
                                {% for fase_projetos in fase_projeto %}
                                    <option value="{{fase_projetos.id}}">{{fase_projetos}}</option>
                                {% endfor %}
                            </select>
                        </div> {% endcomment %}
                    
                    <div class="titulo">
                        <input type="submit" value="Filtrar" class="btn-filtrar_limpar">
                        <input type="submit" value="Limpar" class="btn-filtrar_limpar" name="limpar_filtros">               
                    </div>

                </div>
                </form>
                <br>

                <table class="tabela" cellpadding="20">
                    <tr>
                        <th>Nome Projeto</th>
                        <th>Status</th>
                        <th>Total Tarefas</th>
                        <th>Fase</th>
                        {% comment %} <th>Prioridade</th> {% endcomment %}
                        <th>Ação</th>
                    </tr>

                        {% for projetos in projeto %}
                            
                            
                            <tr {% if not forloop.counter|is_par %} class="tabela-linha" {% endif %} >

                                <td>
                                    <a href="{% url 'projeto_unico' projetos.id %}">{{projetos.nome_projeto}}</a>
                                </td>
                                <td>
                                    {{projetos.status}}
                                </td>
                                <td>
                                    {{ projetos.novatarefa_set.count }}
                                </td>
                                {% comment %} #TODO: incluir as tarefas não concluidas. {% endcomment %}
                                <td>
                                    {{projetos.fase}}
                                </td>
                          
                                <td>

                                    <a href="#editprojetomodal-{{forloop.counter}}" class='bx bxs-edit' style="font-size: 25px; padding: 5px" data-toggle="modal">
                                        <i data-toggle="tooltip" title="Edit">
                                        
                                        </i>
                                    </a>
                                        <form action="#" method="POST" > {% csrf_token %}  
                                        </form>
                                    </i>  
                                  {% include "modal_editar_projeto.html" %} 
                                </td> 
                                
                                
                            </tr>
                        {% endfor %}
                    
                </table> 
            </div>


            

        </div>
    </div>

{% endblock%}